include: package:lint/analysis_options.yaml

# https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart

  strong-mode:
    # Will become the default once non-nullable types land
    # https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # turn on
    prefer_single_quotes: true
    always_put_control_body_on_new_line: true
    avoid_renaming_method_parameters: true
    avoid_slow_async_io: true
    prefer_foreach: true
    sort_constructors_first: true
    unawaited_futures: true

    # turn off
    avoid_print: false
    avoid_classes_with_only_static_members: false
    avoid_setters_without_getters: false
    file_names: false
    join_return_with_assignment: false
    avoid_function_literals_in_foreach_calls: false
    prefer_constructors_over_static_methods: false
    sort_pub_dependencies: false
    # turn off if annoying
    # prefer_final_locals: false
    # prefer_const_constructors: false
