name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  barcode_image: ^2.0.0
  barcode_widget: ^2.0.0
  bonsoir: ^2.0.0
  characters: ^1.2.0
  collection: ^1.16.0
  crypto: ^3.0.0
  device_info: ^2.0.2
  dotted_border: ^2.0.0+2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.2.0
  flutter_markdown: ^0.6.13
  flutter_multi_formatter: ^2.9.11
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html2md: ^1.2.5
  http: ^0.13.5
  image: ^3.2.0
  intl: ^0.18.0
  json_annotation: ^4.3.0
  just_the_tooltip: ^0.0.12
  loading_animation_widget: ^1.2.0+4
  mime_type: ^1.0.0
  open_file: ^3.2.1
  package_info_plus: ^1.4.2
  path: ^1.8.2
  path_provider: ^2.0.9
  pdfx: 2.0.1+2
  provider: ^6.0.5
  random_string: ^2.3.1
  rive: ^0.9.1
  share_extend: ^2.0.0
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1
  supercharged: ^2.0.0
  url_launcher: ^6.1.7
  vector_math: ^2.1.2
  video_player: ^2.4.10
  xml: ^6.0.1

dev_dependencies:
  build_runner: ^2.3.3
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^5.4.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr
