name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  barcode_image: ^2.0.0
  barcode_widget: ^2.0.0
  bonsoir: ^1.0.0+1
  characters: ^1.1.0
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.0
  device_info: ^2.0.2
  dotted_border: ^2.0.0+1
  email_validator: ^2.0.1
  extended_image: ^4.0.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_archive: ^4.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^0.5.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_multi_formatter: ^2.3.3
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^0.22.0
  google_fonts: ^2.0.0
  hex: ^0.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.1.0
  mime_type: ^1.0.0
  native_pdf_renderer: ^3.1.0
  open_file:
    git: git://github.com/crazecoder/open_file
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  random_string: ^2.3.1
  share_extend:
    git: git://github.com/finroly/ShareExtend.git
  shared_preferences: ^2.0.6
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  url_launcher: ^6.0.8
  vector_math: ^2.1.0
  video_player: ^2.1.12
  xml: ^5.2.0
  # just_the_tooltip: ^0.0.7+3
  just_the_tooltip:  
    git: git://github.com/sgehrman/just_the_tooltip
    # path: ../../forks/just_the_tooltip

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr



