name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  barcode_image: ^2.0.0
  barcode_widget: ^2.0.0
  bonsoir: ^1.0.1+2
  characters: ^1.1.0
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.0
  device_info: ^2.0.2
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  extended_image: ^4.1.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_archive: ^4.1.1
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.0.3
  flutter_multi_formatter: ^2.5.1
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.0.0
  google_fonts: ^2.2.0
  hex: ^0.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.3.0
  mime_type: ^1.0.0
  native_pdf_renderer: ^4.0.0
  open_file:
    git: https://github.com/crazecoder/open_file
  package_info: ^2.0.2
  path: ^1.8.1
  path_provider: ^2.0.7
  provider: ^6.0.2
  random_string: ^2.3.1
  share_extend:
    git: https://github.com/finroly/ShareExtend.git
  shared_preferences: ^2.0.9
  simple_animations: ^4.0.1
  supercharged: ^2.0.0
  url_launcher: ^6.0.15
  vector_math: ^2.1.0
  video_player: ^2.2.10
  xml: ^5.2.0
  just_the_tooltip: ^0.0.11+1
  html2md: ^1.2.5
  flutter_markdown: ^0.6.9

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints

flutter:
  uses-material-design: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr
