name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  date_time_format: ^2.0.1
  dfc_dart:
    git: https://github.com/sgehrman/dfc_dart.git
  dotted_border: ^3.1.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate:
    git: https://github.com/sgehrman/flutter_animate.git
  flutter_archive: ^6.0.3
  flutter_carousel_widget: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  flutter_multi_formatter: ^2.13.10
  flutter_svg: ^2.2.1
  flutter_widget_from_html: ^0.17.1
  google_fonts: ^6.3.2
  hex: ^0.2.0
  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2
  html: ^0.15.6
  html2md: ^1.3.2
  http: ^1.5.0
  intl: ">=0.20.2"
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  mime_type: ^1.0.1
  open_file: ^3.5.10
  package_info_plus: ^9.0.0
  pasteboard: ^0.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  random_string: ^2.3.1
  seo: ^0.0.10
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  vector_graphics: ^1.1.19
  vector_math: ^2.2.0
  video_player: ^2.10.0
  web: ^1.1.1
  widget_mask: ^1.0.0+0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.7.1
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints.git
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  # for flutter_localizations
  generate: true

  assets:
    - assets/team_images/
