name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.3
  bonsoir: ^2.0.0
  characters: ^1.2.0
  collection: ^1.17.1
  crypto: ^3.0.0
  device_info_plus: ^9.0.0
  dfc_dart:
    git: https://github.com/sgehrman/dfc_dart
  dotted_border: ^2.0.0+2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_archive: ^5.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_markdown: ^0.6.16
  flutter_multi_formatter: ^2.9.11
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.4
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.1
  html2md: ^1.2.5
  http: ^0.13.5
  image: ^4.0.15
  intl: ^0.18.0
  jovial_svg: ^1.1.12
  json_annotation: ^4.8.0
  just_the_tooltip: ^0.0.12
  linkify: ^5.0.0
  loading_animation_widget: ^1.2.0+4
  mime_type: ^1.0.0
  open_file_plus: ^3.4.0
  package_info_plus: ^4.0.2
  pasteboard: ^0.2.0
  path: ^1.8.2
  path_provider: ^2.0.9
  provider: ^6.0.5
  random_string: ^2.3.1
  share_extend: ^2.0.0
  shared_preferences: ^2.2.0
  supercharged: ^2.0.0
  url_launcher: ^6.1.7
  vector_math: ^2.1.2
  video_player: ^2.7.0
  xml: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.6
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^5.7.5
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr
