name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  barcode_image: ^2.0.0
  barcode_widget: ^2.0.0
  bonsoir: ^1.0.1+2
  characters: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  device_info: ^2.0.2
  dotted_border: ^2.0.0+2
  email_validator: ^2.0.1
  extended_image: ^4.1.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_archive: ^4.1.1
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.2.0
  flutter_markdown: ^0.6.10
  flutter_multi_formatter: ^2.5.1
  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.0.0
  google_fonts: ^2.3.1
  hex: ^0.2.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  html2md: ^1.2.5
  http: ^0.13.3
  image: ^3.1.3
  intl: ^0.17.0
  json_annotation: ^4.3.0
  just_the_tooltip: ^0.0.11+1
  loading_animation_widget: ^1.1.0+3
  mime_type: ^1.0.0
  open_file:
    git: https://github.com/crazecoder/open_file
  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.9
  pdfx: ^2.0.1+1
  provider: ^6.0.2
  random_string: ^2.3.1
  share_extend:
    git: https://github.com/finroly/ShareExtend.git
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1
  supercharged: ^2.0.0
  url_launcher: ^6.1.0
  vector_math: ^2.1.1
  video_player: ^2.4.0
  xml: ^5.2.0

dev_dependencies:
  build_runner: ^2.1.10
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr
