name: dfc_flutter
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  bonsoir: ^5.1.11
  characters: ^1.4.0
  collection: ^1.19.0
  crypto: ^3.0.6
  date_time_format: ^2.0.1
  dfc_dart:
    git: https://github.com/sgehrman/dfc_dart
  dotted_border: ^2.1.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_archive: ^6.0.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  flutter_multi_formatter: ^2.13.0
  flutter_svg: ^2.0.17
  flutter_widget_from_html: ^0.16.0
  google_fonts: ^6.2.1
  hex: ^0.2.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  html: ^0.15.5
  html2md: ^1.3.2
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  mime_type: ^1.0.1
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  pasteboard: ^0.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  random_string: ^2.3.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  vector_graphics: ^1.1.18
  vector_math: ^2.1.4
  video_player: ^2.9.3
  web: ^1.1.1
  widget_mask: ^1.0.0+0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.15
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/JonasWanke/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # for flutter_localizations
  generate: true

  assets:
    - packages/dfc_flutter/assets/animations/treasure.flr
    - packages/dfc_flutter/assets/animations/loading.flr
